name: "💎 Component request"
description: Suggest a new component
labels: [component, request]
body:
- type: input
  id: deadline
  attributes:
    label: "When do you need this component?"
    description: "OPTIONAL. Mention events and deadlines, with lead times."
  validations:
    required: false
- type: textarea
  id: purpose
  attributes:
    label: "What is the purpose of this component?"
    description: "Summarize in one well-written sentence. Explicitly connect to a larger business goal."
    render: markdown
  validations:
    required: true
- type: textarea
  id: locations
  attributes:
    label: "Which templates or pages might use this component?"
  validations:
    required: true
- type: textarea
  id: content
  attributes:
    label: "In terms of content and functionality, what must, should, or could be included?"
    description: "Make a bulleted list, even if you have other documents or a mockup."
    value: |
      **Must**
      Required by law or policy—please provide a link to more information

      - 

      **Should**
      Needed to achieve goals an provide a good experience

      - 

      **Could**
      Nice to have in the first version

      - 

      If you have other wishlists, drafts, wireframes, rough content, research, data, competitive audits, inspiration links, etc., attach or link to them here.
  validations:
    required: true
- type: textarea
  id: research
  attributes:
    label: "What sort of research or data might help us make a business case for this?"
    description: "OPTIONAL. Summarize in bullet points. Attach or link to supporting information."
  validations:
    required: false
